# Generated by Django 5.1.6 on 2025-02-08 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Aktywne'), ('inactive', 'Nieaktywne')], default='active', max_length=10)),
                ('category', models.CharField(choices=[('tech', 'Technologia'), ('real_estate', 'Nieruchomości'), ('jobs', 'Praca'), ('others', 'Inne')], max_length=20)),
                ('author', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Podaj numer telefonu lub adres email!', regex='^(\\+?\\d{9,15}|[\\w.%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,})$')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/')),
            ],
        ),
    ]
